version: "3" # Version của docker-compose, khuyến khích dùng 3

services: # Khai báo các service
  wordpress:
    image: wordpress:5.6-php7.4 # Image của service, kèm version. (được public trên docker hub)
    environment: # Khai báo các biến môi trường của service
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
    volumes: # Khai báo các volume của service, được mount vào container; sẽ không mất đi khi container bị xóa
      - wordpress:/var/www/html
    ports:
      - "8080:80" # Khai báo port của service, sẽ được map sang port của host
    restart: always # Khai báo cách restart container khi container bị down
    depends_on: # Khai báo thứ tự chạy các service, ví dụ ở đây: sẽ chỉ chạy 'wordpress' khi 'db' đã chạy xong
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123456
    volumes:
      - db:/var/lib/mysql
    restart: always # Khai báo cách restart container khi container bị down

volumes:
  wordpress:
  db:
